color0 #15130e
color1 #ffb4ab
color2 #dfc64c
color3 #d1c6a2
color4 #a9d0b4
color5 #dfc64c
color6 #d1c6a2
color7 #e7e2d9
color8 #969080
color9 #ffb4ab
color10 #dfc64c
color11 #d1c6a2
color12 #a9d0b4
color13 #dfc64c
color14 #d1c6a2
color15 #e7e2d9

cursor                #e7e2d9
cursor_text_color     #15130e
background            #15130e
foreground            #e7e2d9
selection_foreground  #cdc6b4
selection_background  #4b4739
active_border_color   #dfc64c
inactive_border_color #4b4739
url_color             #dfc64c

active_tab_foreground   #393000
active_tab_background   #dfc64c
inactive_tab_foreground #cdc6b4
inactive_tab_background #4b4739
cursor_trail_color      #cdc6b4
